### ISSUE TITLE
AWS Bedrock Anthropic Sonnet 4 not working with latest aider 0.84.0

### ISSUE THREAD

**Issue by mstrahinski** [Aider-AI/aider#4175]
### Issue

Same with me, I've also experienced this one:

Aider v0.84.0
Model: bedrock/anthropic.claude-sonnet-4 with whole edit format
Git repo: .git with 2,917 files
Warning: For large repos, consider using --subtree-only and .aiderignore
See: https://aider.chat/docs/faq.html#can-i-use-aider-in-a-large-mono-repo
Repo-map: using 1024 tokens, auto refresh
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

just say hi back to me

litellm.APIConnectionError: 'AmazonAnthropicConfig' object has no attribute 'aws_authentication_params'
Traceback (most recent call last):
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\main.py", line 2768, in completion
response = base_llm_http_handler.completion(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\llms\custom_httpx\llm_http_handler.py", line 270, in completion
data = provider_config.transform_request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\llms\bedrock\chat\invoke_transformations\base_invoke_transformation.py", line 201, in transform_request
inference_params = {
^
File "C:\Users\Strahinski\aider-env\Lib\site-packages\litellm\llms\bedrock\chat\invoke_transformations\base_invoke_transformation.py", line 204, in
if k not in self.aws_authentication_params
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AmazonAnthropicConfig' object has no attribute 'aws_authentication_params'

**Comment by max-rousseau** [comment]
That doesn't look like the right model, I think in bedrock now they require you use an inference profile for Claude 4. That would be `us.anthropic.claude-sonnet-4-20250514-v1:0` or similar.

**Comment by pkozikow** [comment]
> That doesn't look like the right model, I think in bedrock now they require you use an inference profile for Claude 4. That would be `us.anthropic.claude-sonnet-4-20250514-v1:0` or similar.

That's how aider reports it. The actual model is the one you point out. This is the command I'm running:
```
aider --model bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0 --vim --watch-files --no-show-model-warnings --no-auto-commits --cache-prompts $@
```

The same command works with Sonnet 3.7 and Opus 4 (e.g. "aider --model bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0")

It's still happening with this config as reported by Aider on start-up:
```
Aider v0.84.0
Main model: bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0 with diff edit format, prompt cache, infinite output
Weak model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
Git repo: .git with 231 files
Repo-map: using 4096 tokens, files refresh
```
