### ISSUE TITLE
extra_headers no longer working in 0.58.1

### ISSUE THREAD

**Issue by kiorull** [Aider-AI/aider#1955]
### Issue

First of all thanks a lot for the great work! 

This is a small issue, probably affecting a very small number of people.

I am using aider with a custom azure deployment which requires a field in the extra_headers.
I have been using 0.56.0, with a custom .aider.model.settings.yml, in which I have:
- name: "azure/gpt-4o-128k"
  ...
  extra_headers:
    my_mandatory_field: my_mandatory_value

After upgrade:
> Error loading aider model settings: Error loading model settings from .aider.model.settings.yml: ModelSettings.__init__() got an unexpected keyword argument 'extra_headers'  
> Aider v0.58.1  
> Model: azure/gpt-4o-128k with diff edit format  

This setting is supported by litellm.

For the time being I downgraded to 0.56.0.

Thanks again for the great work!

### Version and model info

> Aider v0.58.1  
> Model: azure/gpt-4o-128k with diff edit format

**Comment by fry69** [comment]
Thank you for filing this issue.

I think you now need to specify `extra_params` not `extra_headers` anymore, see here -> https://github.com/Aider-AI/aider/blob/main/HISTORY.md?plain=1#L42

**Comment by kiorull** [comment]
worked perfectly, thank you!
